-- Generated by supabase/seed-from-json.mjs from clubs.json + events.json.
-- 7 runs. Safe to re-run: upserts on slug.

insert into public.runs (slug, category_key, type_key, kind, name, location_name, lat, lng, freebies, cost, price, day_of_week, event_date, time, register_link, photos, notes, details, last_updated) values
  ('on-run-club-recurring', 'running', 'social', 'recurring'::public.run_kind, 'ON Run Club', 'Orto Cafe, Jumeirah', 25.1950095, 55.2357981, true, null, '', 'saturday', null, '05:45', 'https://onrunclubdxb.splashthat.eu', array[]::text[], '', '{"surface":"road","pace":"easy / social"}'::jsonb, '2026-08-05'),
  ('the-uncommon-club-recurring', 'running', 'social', 'recurring'::public.run_kind, 'The Uncommon Club', 'Feels, Kite Beach', 25.185185, 55.224511, true, null, '', 'thursday', null, '05:00', 'https://www.instagram.com/theeuncommonclub', array[]::text[], '', '{"surface":"beach","pace":"easy / social"}'::jsonb, '2026-08-31'),
  ('frame-run-club-recurring', 'running', 'training', 'recurring'::public.run_kind, 'Frame Run Club', 'Dubai Design District', 25.1866742, 55.3019726, false, null, '', 'wednesday', null, '19:30', 'https://www.instagram.com/framerunclub', array[]::text[], '', '{"surface":"road","pace":"training"}'::jsonb, '2026-08-05'),
  ('lfg-recurring', 'running', 'training', 'recurring'::public.run_kind, 'LFG', 'Gems World Academy', 25.08245633476715, 55.21956164418061, false, null, '', 'wednesday', null, '19:30', 'https://www.instagram.com/lfgdubai?igsh=NzhpbmJsZTU3NnIx', array[]::text[], '', '{"surface":"track","pace":"training"}'::jsonb, '2026-08-07'),
  ('kin-runclub-recurring', 'running', 'social', 'recurring'::public.run_kind, 'Kin RunClub', 'Toga Coffee', 25.309316, 55.467763, true, null, '', 'saturday', null, '05:45', 'https://www.instagram.com/kinclub.ae?igsi=eWk0NHV4MDhjNXNt', array[]::text[], '', '{"surface":"road"}'::jsonb, '2026-08-26'),
  ('spartan-run-club-recurring', 'running', 'social', 'recurring'::public.run_kind, 'Spartan Run Club', 'Bluewaters, Dubai', 25.079388, 55.123719, true, 'free', '', 'saturday', null, '06:00', 'https://www.instagram.com/spartanmiddleeast?stkn=MThjc2p1ZGd2MTMwcQ==', array['https://raw.githubusercontent.com/tahashi-exe/velocity-dashboard/main/club-photos/s0ydfy20.jpg']::text[], 'Run with SRC and Drinks plus socials at Joe and the Juice after', '{"surface":"road"}'::jsonb, '2026-09-09'),
  ('ono-one-night-only-track-session-one_off', 'running', 'training', 'one_off'::public.run_kind, 'ONO- One night only Track session', 'Dubai American Academy', 25.104510738680734, 55.1811096116243, true, null, '', null, '2026-08-14', '19:00', 'https://www.instagram.com/onotrackdxb?igsh=bG13OHk3MmE3YXo0', array[]::text[], '', '{"surface":"track","pace":"training"}'::jsonb, '2026-08-14')
on conflict (slug) do update set
  category_key = excluded.category_key,
  type_key = excluded.type_key,
  kind = excluded.kind,
  name = excluded.name,
  location_name = excluded.location_name,
  lat = excluded.lat,
  lng = excluded.lng,
  freebies = excluded.freebies,
  cost = excluded.cost,
  price = excluded.price,
  day_of_week = excluded.day_of_week,
  event_date = excluded.event_date,
  time = excluded.time,
  register_link = excluded.register_link,
  photos = excluded.photos,
  notes = excluded.notes,
  details = excluded.details,
  last_updated = excluded.last_updated;
